# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video = QtWidgets.QPushButton(parent=self.centralwidget)
        self.video.setGeometry(QtCore.QRect(30, 20, 111, 61))
        font = QtGui.QFont()
        font.setKerning(True)
        self.video.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("youtube.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.video.setIcon(icon)
        self.video.setIconSize(QtCore.QSize(40, 40))
        self.video.setCheckable(False)
        self.video.setObjectName("video")
        self.show_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.show_video.setGeometry(QtCore.QRect(30, 90, 1000, 580))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        self.show_video.setFont(font)
        self.show_video.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.show_video.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.show_video.setAutoFillBackground(False)
        self.show_video.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.show_video.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.show_video.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.show_video.setObjectName("show_video")
        self.show_path = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.show_path.setGeometry(QtCore.QRect(150, 25, 881, 51))
        self.show_path.setAutoFillBackground(False)
        self.show_path.setObjectName("show_path")
        self.alarm_history = QtWidgets.QListWidget(parent=self.centralwidget)
        self.alarm_history.setGeometry(QtCore.QRect(1040, 25, 231, 645))
        self.alarm_history.setObjectName("alarm_history")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.video.setText(_translate("MainWindow", "Video"))
        self.show_video.setText(_translate("MainWindow", "Select Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
